kind: Service
apiVersion: v1
metadata:
# set your user name
  name:  {{ .Chart.Name }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.service.servicePort }}
      targetPort: {{ .Values.service.servicePort }}
  selector:
# set your user name
    app:  {{ .Chart.Name }}